Book_Store_Proj_manifest/force-app/main/default/objects/Error_Log_Event__e/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <label>Class Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Book_Store_Proj_manifest/force-app/main/default/objects/Error_Log_Event__e/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <label>Exception Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Book_Store_Proj_manifest/force-app/main/default/objects/Error_Log_Event__e/fields/Initiated_By_User__c.field-meta.xml
<CustomField>
    <fullName>Initiated_By_User__c</fullName>
    <label>Initiated By User</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Book_Store_Proj_manifest/force-app/main/default/classes/LogExecptionUtill.cls
/*
**************************************************************************
Apex class Name    : LogExecptionUtill
Created Date       : November 10, 2024
@description       : This is used to cstore exception log
@author            : Pradeep Kumar Reddy Dhanireddy

Modification Log:
Ver   Date         Author                               Modification
1.0   11-10-2024   Pradeep Kumar Reddy Dhanireddy       Initial Version
**************************************************************************
*/
public class LogExecptionUtill {
    /*
    **************************************************************
    @Method Name    : createErrorLog
    @author         : Pradeep Kumar Reddy Dhanireddy
    @description    : method to is used to publish Error Log Event 
    @param          : String className , String methodName, String errorMessage 
    @return         : null
    **************************************************************
    */
    public static void createErrorLog(String className , String methodName, String errorMessage ){
        Error_Log_Event__e errLogEvt = new Error_Log_Event__e();
        errLogEvt.Class_Name__c = className;
        errLogEvt.Method_Name__c = methodName;
        errLogEvt.Exception_Message__c = errorMessage;
        errLogEvt.Initiated_By_User__c = userinfo.getuserid();
        EventBus.Publish(errLogEvt);
    }
    
}